title: National Library Exhibitions
title-abbreviated: National Library Exhibitions
description: "Exhibitions organised National Library Singapore"
url: "https://exhibitions.nlb.gov.sg/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
resources_name: "exhibitions"
paginate: 12
paginate_path: "/exhibitons/page:num"

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: true

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"


collections:
  current-exhibitions:
    output: true
  online-exhibitions:
    output: true
  past-exhibition:
    output: true
resources_name: exhibitions
